import type { Investigation } from '@/data/investigation'
import type { Problem } from '@/data/types'

/** Susun dossier investigasi (Markdown) lalu unduh sebagai file. */
export function exportDossier(problem: Problem & { ahp: number }, inv: Investigation, series: Record<string, number[]>) {
  const lines = [
    `# Investigation Dossier — ${problem.id}`,
    '',
    `**${inv.headline}** · ${inv.assetType} · ${inv.location}`,
    '',
    `- Severity: ${problem.severity.toUpperCase()} (AHP ${problem.ahp.toFixed(2)})`,
    `- Status: ${problem.status} · Lead: ${problem.lead}`,
    `- Detected: ${new Date(problem.detectedAt).toLocaleString('en-GB', { timeZone: 'Asia/Jakarta' })} WIB`,
    `- Failure mode hypothesis: ${inv.failureMode}`,
    '',
    '## Relevant parameters',
    '',
    '| Tag | Parameter | Current | Change | Limits | Status |',
    '|---|---|---|---|---|---|',
    ...inv.params.map((p) => {
      const s = series[p.key]
      const v = s[s.length - 1].toFixed(p.digits)
      return `| ${p.tag} | ${p.label} | ${v} ${p.unit} | ${p.delta.text} | ${p.limits.map((l) => `${l.label} ${l.value}`).join(', ')} | ${p.status.label} |`
    }),
    '',
    '## Impact translation',
    '',
    ...inv.impact.map((s, i) => `${i + 1}. **${s.title}** — ${s.headline} (${s.detail})`),
    '',
    `## Data confidence: ${inv.confidence.pct}%`,
    '',
    inv.confidence.note,
    '',
    '## Similar historical incidents',
    '',
    ...inv.incidents.map((r) => `- **${r.id}** (${r.equipment}, ${r.similarity}% match) — ${r.mechanism}. RCA: ${r.rca.cause}. Fix: ${r.rca.fix}`),
    '',
    `_Sources: ${inv.sources.join(' · ')} · Generated by CALIBER on ${new Date().toLocaleString('en-GB')}_`,
  ]

  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${problem.id}-investigation-dossier.md`
  a.click()
  URL.revokeObjectURL(url)
}
