import type { Asset } from '@/data/dataset'
import type { Investigation } from '@/data/investigation'
import { fmtValue } from '@/data/plant'
import type { AuditEntry, Hypothesis } from '@/data/rootCause'
import type { Problem } from '@/data/types'
import { RC_AHP, RC_CRITERIA, rcWeight } from './ahpPairwise'
import { fmtDate } from './asOf'
import type { HypothesisDecision } from './useDecision'

/** Susun dossier investigasi (Markdown) pada tanggal replay lalu unduh sebagai file. */
export function exportDossier(problem: Problem & { ahp: number }, inv: Investigation, asOf: string) {
  const a = inv.asset
  const lines = [
    `# Investigation Dossier — ${a.tag}`,
    '',
    `**${a.name}** · ${a.type} · ${a.plantName} · Class ${a.eqClass}`,
    `Data as of ${fmtDate(asOf)} (source: competition dataset)`,
    '',
    `- Health phase: ${inv.health.phase} · Severity: ${problem.severity.toUpperCase()} (AHP ${problem.ahp.toFixed(2)})`,
    `- Status: ${problem.status} · RCA PIC: ${problem.lead}`,
    '',
    '## Condition monitoring (latest weekly reading)',
    '',
    '| Parameter | Value | Alarm | Trip | 4-wk change | Projection |',
    '|---|---|---|---|---|---|',
    ...inv.health.params.map(
      (p) =>
        `| ${p.param.label} | ${fmtValue(p.param, p.value)} ${p.param.unit} | ${p.param.alarm} | ${p.param.trip} | ${p.changePct.toFixed(0)}% | ${
          p.daysToTrip ? `trip in ~${p.daysToTrip} d` : p.daysToAlarm ? `alarm in ~${p.daysToAlarm} d` : '—'
        } |`,
    ),
    '',
    '## Impact translation',
    '',
    ...inv.impact.map((s, i) => `${i + 1}. **${s.title}** — ${s.headline} (${s.detail})`),
    '',
    `## Data confidence: ${inv.confidence.pct}%`,
    '',
    inv.confidence.note,
    '',
    '## Similar historical incidents (Incident Database)',
    '',
    ...inv.incidents
      .slice(0, 8)
      .map((s) => `- **${s.incident.ar ?? s.incident.mto}** ${s.incident.tag} (${s.incident.plant}) — ${s.incident.title}; ${Math.round(s.score * 100)}% match; ${s.incident.downtimeH} h, $${s.incident.totalLossK}k; ${s.incident.status}`),
    '',
    `_Sources: ${inv.sources.join(' · ')} · Generated by CALIBER on ${new Date().toLocaleString('en-GB')}_`,
  ]
  download(lines, `${a.tag}-investigation-dossier.md`)
}

/** Dossier RCA: ranking hipotesis AHP, keputusan engineer, CAPA, dan audit trail. */
export function exportRcaDossier(
  problem: Problem,
  a: Asset,
  ranked: (Hypothesis & { priority: number })[],
  decisions: Record<string, HypothesisDecision>,
  audit: AuditEntry[],
) {
  const rca = a.rca
  const lines = [
    `# RCA Dossier — ${a.tag} (${rca?.arNo ?? ''})`,
    '',
    `${a.name} · ${a.plantName} · RCA PIC: ${problem.lead}`,
    rca ? `Problem statement: ${rca.problemStatement}` : '',
    '',
    `## AHP criteria weights (CR = ${RC_AHP.cr.toFixed(3)})`,
    '',
    ...RC_CRITERIA.map((c) => `- ${c.label}: ${(rcWeight(c.key) * 100).toFixed(1)}%`),
    '',
    '## Ranked hypotheses',
    '',
    '| Rank | ID | Hypothesis | AHP score | Confidence | Decision |',
    '|---|---|---|---|---|---|',
    ...ranked.map((h, i) => `| ${i + 1} | ${h.id} | ${h.title} | ${h.priority.toFixed(2)} | ${h.confidence}% | ${decisions[h.id] ?? 'pending'} |`),
    '',
    ...ranked.flatMap((h) => [`### ${h.id} — ${h.title}`, '', h.summary, '', ...h.evidence.map((e) => `- [${e.status}] ${e.text} (${e.source})`), '']),
    ...(rca
      ? ['## CAPA', '', ...rca.actions.map((x) => `- [${x.kind}] ${x.rc}: ${x.text} — ${x.pic}, plan ${x.planDate}, ${x.status ?? 'planned'}`), '']
      : []),
    '## Decision audit trail',
    '',
    ...audit.map((e) => `- ${e.time} · **${e.actor}** — ${e.text}`),
    '',
    `_Generated by CALIBER on ${new Date().toLocaleString('en-GB')}_`,
  ]
  download(lines, `${a.tag}-rca-dossier.md`)
}

function download(lines: string[], filename: string) {
  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.click()
  URL.revokeObjectURL(url)
}
