import type { Investigation } from '@/data/investigation'
import type { AuditEntry, Hypothesis } from '@/data/rootCause'
import type { Problem } from '@/data/types'
import { RC_AHP, RC_CRITERIA, rcWeight } from './ahpPairwise'
import type { HypothesisDecision } from './useDecision'

/** Susun dossier investigasi (Markdown) lalu unduh sebagai file. */
export function exportDossier(problem: Problem & { ahp: number }, inv: Investigation, series: Record<string, number[]>) {
  const lines = [
    `# Investigation Dossier — ${problem.id}`,
    '',
    `**${inv.headline}** · ${inv.assetType} · ${inv.location}`,
    '',
    `- Severity: ${problem.severity.toUpperCase()} (AHP ${problem.ahp.toFixed(2)})`,
    `- Status: ${problem.status} · Lead: ${problem.lead}`,
    `- Detected: ${new Date(problem.detectedAt).toLocaleString('en-GB', { timeZone: 'Asia/Jakarta' })} WIB`,
    `- Failure mode hypothesis: ${inv.failureMode}`,
    '',
    '## Relevant parameters',
    '',
    '| Tag | Parameter | Current | Change | Limits | Status |',
    '|---|---|---|---|---|---|',
    ...inv.params.map((p) => {
      const s = series[p.key]
      const v = s[s.length - 1].toFixed(p.digits)
      return `| ${p.tag} | ${p.label} | ${v} ${p.unit} | ${p.delta.text} | ${p.limits.map((l) => `${l.label} ${l.value}`).join(', ')} | ${p.status.label} |`
    }),
    '',
    '## Impact translation',
    '',
    ...inv.impact.map((s, i) => `${i + 1}. **${s.title}** — ${s.headline} (${s.detail})`),
    '',
    `## Data confidence: ${inv.confidence.pct}%`,
    '',
    inv.confidence.note,
    '',
    '## Similar historical incidents',
    '',
    ...inv.incidents.map((r) => `- **${r.id}** (${r.equipment}, ${r.similarity}% match) — ${r.mechanism}. RCA: ${r.rca.cause}. Fix: ${r.rca.fix}`),
    '',
    `_Sources: ${inv.sources.join(' · ')} · Generated by CALIBER on ${new Date().toLocaleString('en-GB')}_`,
  ]
  download(lines, `${problem.id}-investigation-dossier.md`)
}

/** Dossier RCA: ranking hipotesis AHP, keputusan engineer, dan audit trail. */
export function exportRcaDossier(
  problem: Problem,
  inv: Investigation,
  ranked: (Hypothesis & { priority: number })[],
  decisions: Record<string, HypothesisDecision>,
  audit: AuditEntry[],
) {
  const lines = [
    `# RCA Dossier — ${problem.id}`,
    '',
    `${inv.assetType} · ${inv.location} · Lead: ${problem.lead}`,
    '',
    `## AHP criteria weights (CR = ${RC_AHP.cr.toFixed(3)})`,
    '',
    ...RC_CRITERIA.map((c) => `- ${c.label}: ${(rcWeight(c.key) * 100).toFixed(1)}%`),
    '',
    '## Ranked hypotheses',
    '',
    '| Rank | ID | Hypothesis | AHP score | Confidence | Decision |',
    '|---|---|---|---|---|---|',
    ...ranked.map((h, i) => `| ${i + 1} | ${h.id} | ${h.title} | ${h.priority.toFixed(2)} | ${h.confidence}% | ${decisions[h.id] ?? 'pending'} |`),
    '',
    ...ranked.flatMap((h) => [`### ${h.id} — ${h.title}`, '', h.summary, '', ...h.evidence.map((e) => `- [${e.status}] ${e.text} (${e.source})`), '']),
    '## Decision audit trail',
    '',
    ...audit.map((a) => `- ${a.time} WIB · **${a.actor}** — ${a.text}`),
    '',
    `_Generated by CALIBER on ${new Date().toLocaleString('en-GB')}_`,
  ]
  download(lines, `${problem.id}-rca-dossier.md`)
}

function download(lines: string[], filename: string) {
  const blob = new Blob([lines.join('\n')], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
